import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { headers } from "next/headers";

import { cookieToInitialState } from "wagmi";

const sans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta-sans",
});

import "@nexus-studio/ui/globals.css";

import { getWagmiConfig } from "@/lib/wagmi";
import { ProviderTree } from "@/providers";

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const RootLayout = async (props: LayoutProps<"/">) => {
  const initialState = cookieToInitialState(
    getWagmiConfig(),
    (await headers()).get("cookie"),
  );

  return (
    <html
      className={`${sans.variable} antialiased`}
      lang="en"
      suppressHydrationWarning={true}
    >
      <body>
        <ProviderTree initialState={initialState}>
          {props.children}
        </ProviderTree>
      </body>
    </html>
  );
};

export default RootLayout;
