import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";

const sans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-jakarta-sans",
});

import "@nexus-studio/ui/globals.css";

import { Navbar } from "@/components";
import { ProviderTree } from "@/providers";

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const RootLayout = (props: LayoutProps<"/">) => {
  return (
    <html
      className={`${sans.variable} antialiased`}
      lang="en"
      suppressHydrationWarning={true}
    >
      <body>
        <ProviderTree>
          <div className="h-screen">
            <Navbar />
            {props.children}
          </div>
        </ProviderTree>
      </body>
    </html>
  );
};

export default RootLayout;
